#!/bin/bash

CH_NAMESPACE="${CH_NAMESPACE:-chista-operator}"

CUR_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

kubectl create namespace "${CH_NAMESPACE}"

kubectl apply -n "${CH_NAMESPACE}" -f "${CUR_DIR}/operator.yaml"
